// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'intro',
    'configuration',
    'usage',
    {
      type: 'category',
      label: 'Design Decisions',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'adr/README',
      },
      items: [
        { type: 'autogenerated', dirName: 'adr' },
      ],
    },
  ],
};

module.exports = sidebars;
