{{- if not .Values.useStatefulSet }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "docker-registry.fullname" . }}
  namespace: {{ include "docker-registry.namespace" . }}
  labels:
    {{- include "docker-registry.labels.merged" (dict "ctx" . "extra" .Values.deployment.labels) | nindent 4 }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "docker-registry.match-labels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  minReadySeconds: 5
  template:
  {{- include "docker-registry.podTemplate" . }}
{{- end }}
