{{- if .Values.httproute.enabled -}}
{{- $route := .Values.httproute -}}
{{- $serviceName := .Values.service.name | default (include "docker-registry.fullname" .) -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: {{ $route.apiVersion | default "gateway.networking.k8s.io/v1" }}
kind: HTTPRoute
metadata:
  name: {{ template "docker-registry.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
{{- if $route.labels }}
{{ toYaml $route.labels | indent 4 }}
{{- end }}
{{- if $route.annotations }}
  annotations:
    {{- range $key, $value := $route.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- with $route.additionalRules }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: {{ $serviceName }}
          port: {{ $servicePort }}
      {{- with $route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
