{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "docker-registry.fullname" . }}-podmonitor
  labels:
    {{- include "docker-registry.labels.merged" (dict "ctx" . "extra" .Values.metrics.podMonitor.labels) | nindent 4 }}
spec:
  podMetricsEndpoints:
  - interval: 15s
    port: http-metrics
  selector:
    matchLabels:
      {{- include "docker-registry.match-labels" . | nindent 6 }}
{{- end }}
