{{- if .Values.useStatefulSet }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "docker-registry.fullname" . }}
  namespace: {{ include "docker-registry.namespace" . }}
  labels:
    {{- include "docker-registry.labels.merged" (dict "ctx" . "extra" .Values.deployment.labels) | nindent 4 }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "docker-registry.match-labels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "docker-registry.fullname" . }}
  {{- if .Values.updateStrategy }}
  updateStrategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  minReadySeconds: 5
  template:
  {{- include "docker-registry.podTemplate" . }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      # Must match the "data" volume name used in _helpers.tpl
      # (storage == "filesystem").
      name: data
      labels:
        {{- include "docker-registry.labels" . | nindent 8 }}
      {{- with .Values.persistence.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      {{- if .Values.persistence.volumeName }}
      volumeName: {{ .Values.persistence.volumeName | quote }}
      {{- end }}
  {{- end }}
{{- end }}
